### ISSUE TITLE
Save/Preview not taking

### ISSUE THREAD

**Issue by BigActual** [joelworsham/cd-new-temp#1]
I attempted to save changes and they didn't take. tried previewing and saving and that did not help.

**Comment by joelworsham** [comment]
Hmmm I tested and it is working. The UX is currently quite crude and I plan on making it far more clear. Perhaps you didn't do exactly what you thought?

**Comment by BigActual** [comment]
Possible.

**Comment by joelworsham** [comment]
@BigActual Still happening?

**Comment by BigActual** [comment]
Nope. It's good. Glad you closed it.
