### ISSUE TITLE
Customizer should not be viewable

### ISSUE THREAD

**Issue by d4mation** [joelworsham/cd-new-temp#6]
It looks silly and isn't exactly "Within the admin".

![image](https://cloud.githubusercontent.com/assets/7770631/23514081/302241e6-ff34-11e6-9f9b-a28cb95979d4.png)

Maybe it could be added to however you are handling this?

![image](https://cloud.githubusercontent.com/assets/7770631/23514163/6ea3519e-ff34-11e6-99ee-1741a7ec2fe4.png)

**Comment by joelworsham** [comment]
Yeah, the reason it isn't blocked is because the link has `wp-admin` in it, `wp-admin/customize.php`. I'll block that link directly.
