### ISSUE TITLE
Using fetch

### ISSUE THREAD

**Issue by d4mation** [joelworsham/cd-new-temp#9]
I was looking at how you were handling the Rest API here for another project and I noticed you were using `fetch`. Looks like it will block out IE 11 users, which is still somewhat recent of a version :/

http://caniuse.com/#search=fetch

Also, I have to:

![image](https://cloud.githubusercontent.com/assets/7770631/23754801/4bf98b90-04ac-11e7-969e-813234c0a717.png)

**Comment by joelworsham** [comment]
I'm glad you did that. I remember wondering if it was usable, and decided it was... not sure why I would have in this case? I need to look into it. It could be that my compiler is changing it? Not sure...

**Comment by joelworsham** [comment]
Side note: `fetch()` is freaking awesome.

**Comment by joelworsham** [comment]
Going to implement a polyfill. See #10
